### ISSUE TITLE
Spread operator failed jest tests

### ISSUE THREAD

**Issue by dmitry-saritasa** [vuejs/vue-template-es2015-compiler#12]
```
 FAIL  src/apps/auth/components/sign-up.unit.js
  ● Test suite failed to run

    Object spread operator requires specified objectAssign option with 'Object.assign' or polyfill helper. (1:412)
      
      at Node.transpile (node_modules/vue-template-es2015-compiler/buble.js:12676:11)
      at node_modules/vue-template-es2015-compiler/buble.js:5864:59
          at Array.forEach (<anonymous>)
      at Node.transpile (node_modules/vue-template-es2015-compiler/buble.js:5864:10)
      at Node.transpile (node_modules/vue-template-es2015-compiler/buble.js:6553:28)
      at node_modules/vue-template-es2015-compiler/buble.js:5864:59
          at Array.forEach (<anonymous>)
      at Node.transpile (node_modules/vue-template-es2015-compiler/buble.js:5864:10)
      at Node.transpile (node_modules/vue-template-es2015-compiler/buble.js:6553:28)

```

### vue-loader.conf.js

```
'use strict'
const utils = require('./utils')
const config = require('../config')
const isProduction = process.env.NODE_ENV === 'production'
const sourceMapEnabled = isProduction
  ? config.build.productionSourceMap
  : config.dev.cssSourceMap

module.exports = {
  loaders: utils.cssLoaders({
    sourceMap: sourceMapEnabled,
    extract: isProduction
  }),
  cssSourceMap: sourceMapEnabled,
  cacheBusting: config.dev.cacheBusting,
  transformToRequire: {
    video: ['src', 'poster'],
    source: 'src',
    img: 'src',
    image: 'xlink:href'
  },
  buble: {
    objectAssign: 'Object.assign'
  }
}
```

and this is example of the template (see **v-on**)
```
<template>
  <!--
    // replaced @input="$emit('input', $event.target.value)" with
    // v-on="$listeners", need testing
    // see more here
    // http://blog.webf.zone/vue-js-considerations-and-tricks-fa7e0e4bb7bb
  -->
  <div>
    <label class="form-label">{{ getLabel | capitalize }}</label>
    <input
      v-tooltip="getTooltipContent"
      :bind="$attrs"
      :type="type"
      :value="value"
      :placeholder="getPlaceHolder"
      :class="getClass"
      class="form-input"
      data-vv-validate-on="none"
      v-on="{
        ...$listeners,
        input: event => $emit('input', event.target.value)
      }">
  </div>
</template>```

**Comment by LinusBorg** [comment]
The spread operator is not supported in template yet. We are working on it in the vue core repo, though.

@vuejs/collaborators  can someone close this?
