### ISSUE TITLE
Assigning to rvalue with directive

### ISSUE THREAD

**Issue by patriciussanctus** [vuejs/vue-template-es2015-compiler#8]
i trying paste my data to v-model, but if i want work with my data into directive => template-compiler failed
vue@2.2.6

```
<template lang="pug">
  my-component(v-model="$clone(testArray)")
</template>

<script>
  // Vue.prototype.$clone = x => JSON.parse(JSON.stringify(x))
  export default {
    data: () => ({
      testArray: [ { id: 1 }, { id: 2 }, { id: 3 } ]
    })
  }
</script>
```

```
in ./~/vue-loader/lib/template-compiler?{"id":"data-v-745bb2fe"}!./~/vue-loader/lib/template-compiler/preprocessor.js?raw&engine=pug!./~/vue-loader/lib/selector.js?type=template&index=0!./source/view/branch/index.vue
Module build failed: SyntaxError: Assigning to rvalue (159:8)
    at Parser.pp$4.raise (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:2231:15)
    at Parser.pp$2.toAssignable (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:1354:14)
    at Parser.pp$3.parseMaybeAssign (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:1614:46)
    at Parser.pp$3.parseExpression (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:1583:21)
    at Parser.pp$1.parseStatement (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:737:47)
    at Parser.pp$1.parseBlock (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:991:25)
    at Parser.pp$3.parseFunctionBody (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:2115:24)
    at Parser.pp$1.parseFunction (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:1075:10)
    at Parser.pp$3.parseExprAtom (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:1820:19)
    at Parser.parseExprAtom (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:3800:24)
    at Parser.pp$3.parseExprSubscripts (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:1725:21)
    at Parser.pp$3.parseMaybeUnary (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:1702:19)
    at Parser.pp$3.parseExprOps (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:1647:21)
    at Parser.pp$3.parseMaybeConditional (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:1630:21)
    at Parser.pp$3.parseMaybeAssign (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:1607:21)
    at Parser.pp$3.parsePropertyValue (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:2008:89)
    at Parser.parseObj (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:3895:14)
    at Parser.pp$3.parseExprAtom (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:1815:19)
    at Parser.parseExprAtom (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:3800:24)
    at Parser.pp$3.parseExprSubscripts (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:1725:21)
    at Parser.pp$3.parseMaybeUnary (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:1702:19)
    at Parser.pp$3.parseExprOps (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:1647:21)
    at Parser.pp$3.parseMaybeConditional (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:1630:21)
    at Parser.pp$3.parseMaybeAssign (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:1607:21)
    at Parser.pp$3.parsePropertyValue (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:2008:89)
    at Parser.parseObj (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:3895:14)
    at Parser.pp$3.parseExprAtom (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:1815:19)
    at Parser.parseExprAtom (/Users/zaaa/node/averia-crm/node_modules/vue-template-es2015-compiler/buble.js:3800:24)
 @ ./source/view/branch/index.vue 5:2-267
 @ ./source/router/menu.js
 @ ./source/router/index.js
 @ ./source/main.js
 @ multi ./build/dev-client ./source/main.js
```

**Comment by yyx990803** [comment]
You can't bind v-model to an unassignable expression.
